blank_issues_enabled: false
contact_links:
  - name: NEW DEVICE OR SOFTWARE SUPPORT
    url: https://github.com/bitfocus/companion-module-requests/issues
    about: Please request new device integrations here.
