name: Check for Builtin modules updates
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Run every week
  schedule:
    - cron: "43 5 * * 0"

env:
  COMPANION_BRANCH: main

permissions:
  contents: write
  pull-requests: write

jobs:
  update-nodejs:
    if: ${{ github.repository_owner == 'bitfocus' }}

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          submodules: true
          ref: ${{ env.COMPANION_BRANCH }}
          token: ${{ secrets.SYNC_MODULES_PAT }}

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: ".node-version"

      - name: Setup environment
        run: |
          corepack enable
          yarn

      - name: Run script
        run: |
          yarn tsx tools/update_builtin_surface_modules.mts

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "chore: update builtin surface modules"
          title: "chore: update builtin surface modules"
          body: "This PR updates the builtin surface modules in the Companion."
          delete-branch: true
          branch: "chore/update-builtin-surface-modules"
          committer: "Companion Bot <companion-module-bot@users.noreply.github.com>"
          author: "Companion Bot <companion-module-bot@users.noreply.github.com>"
          add-paths: |
            assets/builtin-surface-modules.json
          token: ${{ secrets.SYNC_MODULES_PAT }}
